apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: customer-service
spec:
  gateways:
    - my-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: customer-service
            port:
              number: 80